## Local setup
#
#spring:
#  application:
#    name: order-api
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:postgresql://localhost:5432/greenzone
#    username: greenzone
#    password: greenzone
#
#app:
#  jwt:
#    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
#    expiration:
#      minutes: 10
#  cors:
#    allowed-origins: http://localhost:3000, http://localhost:4200
#
#logging:
#  level:
#    org.springframework.security: DEBUG


#Production setup
spring:
  application:
    name: recycling-app
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration:
      minutes: 10
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}

logging:
  level:
    org.springframework.security: DEBUG
server:
  tomcat:
    accesslog:
      enabled: true
config:
  import:
