spring:
  application:
    name: order-api
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://dpg-cnblg6ocmk4c73ahos00-a.oregon-postgres.render.com/greenzone
    username: greenzone
    password: MYQlnDxmQ4mDGsNJKy0U7XSTApu8VNby
    driver-class-name: org.postgresql.Driver

app:
  jwt:
    secret: v9y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVkYp
    expiration:
      minutes: 10
  cors:
    allowed-origins: http://localhost:3000, http://localhost:4200

logging:
  level:
    org.springframework.security: DEBUG
server:
  tomcat:
    accesslog:
      enabled: true